### ISSUE TITLE
Regenerate example figures

### ISSUE THREAD

**Issue by rob-luke** [rob-luke/Neuroimaging.jl#13]
Rather than store figures in the repo, place them here and link.

**Comment by rob-luke** [comment]
![multichannel-timeseries](https://cloud.githubusercontent.com/assets/748691/17362167/210f9c28-5974-11e6-8a05-62fa399d32d1.png)
![singlechannel-timeseries](https://cloud.githubusercontent.com/assets/748691/17362166/210e53f4-5974-11e6-8df0-c2723c65ba52.png)

**Comment by codles** [comment]
![source](https://cloud.githubusercontent.com/assets/748691/17363268/a7677b56-5979-11e6-8ec3-d852c9119e95.png)

**Comment by rob-luke** [comment]
![source](https://cloud.githubusercontent.com/assets/748691/17363374/523373a0-597a-11e6-94d9-826381617756.png)
