### ISSUE TITLE
Epoch: order of dimensions

### ISSUE THREAD

**Issue by behinger** [rob-luke/Neuroimaging.jl#163]
as far as I see, currently Epoch is `trials x times x channels`

Different is eeglab, which has `channel x times x trials`
Also different is MNE, which has `trials x channels x times`
fieldtrip is a bit different, but it uses trials { channels x times }

I like eeglab best because it is what I'm used to ;-) I wonder if there is a reason for your choice.

Cheers, Bene

**Comment by rob-luke** [comment]
I think the epoch structure is `times x epochs x channels` in your terminology.

https://github.com/rob-luke/Neuroimaging.jl/blob/e69bb0bece330b2c5d0b940f38d57081cbc16b8b/src/reshaping/epochs.jl#L70-L75

And running the following code indicates `times x epochs x channels` too

```Julia
using Neuroimaging, DataDeps, Unitful
data_path = joinpath(
    datadep"ExampleSSR",
    "Neuroimaging.jl-example-data-master",
    "neuroimaingSSR.bdf",
)

s = read_SSR(data_path)
s = extract_epochs(s)
size(s.processing["epochs"])
# (8388, 311, 7)
```

This doesn't seem to match your impression, its highly possible that there is conflicting code somewhere, please point this out if you find it.

As to why it was this way, I was heavily using SampledSignals.jl when I wrote this. And it uses `times x channels`. So I found it always easy to remember that channels is the final index regardless of if its raw data or epochs or sweeps etc. Similarly, I always know that time is the first index, doesn't matter if its raw data or epochs etc. To maintain this simplicity I put the extra dimension in the middle.

I think I still like this simplicity, its easy for me to remember which index to use. I know there are benifits to processing and storage for different order of dimensions (see https://github.com/JuliaAudio/SampledSignals.jl/issues/59), but currently the computational benefits are simply outweighed by the reduced mental workload of always knowing first dim is time, last dim is channels.

In the short term maybe it would be good to have some wrapper functions that operate on the epochs like `times(epochs)` that automatically choses the correct dimension. In the long run, an epoch type is probably appropriate, but its not immediately apparent how to interface this with the different data types (GeneralEEG vs SSR). 

As this seemed like more of a question than an issue I will close this thread, feel free to keep discussing here though, but it seems more of a usage and design question than a suggested change or bug (correct me if im wrong)

**Comment by behinger** [comment]
Indeed, I think I missidentified it, sorry!

My argument would be to make it as compatible as possible to what other people have been using - but I will get used to it also. It is just a design decision that can be very hard to change later on

**Comment by rob-luke** [comment]
> as compatible as possible to what other people have been using

I would consider changing to the same as MNE if there was demand for it, that would make sense to me as I think most users are likely to come from there.
