### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by rob-luke** [rob-luke/Neuroimaging.jl#45]
I am thinking `neuroimaging.jl` as I will add support for MEG, fNIRS, etc

**Comment by likanzhan** [comment]
Neuroimaging normally include fMRI, PET, etc. Are we also going to support these?

**Comment by rob-luke** [comment]
Haha I thought that would come up. In my experience neuroimaing only means fMRI to the fMRI people :wink: so I'm fine with taking the general terminology as EEG, MEG, fNIRS covers a fair range of the field. And I would like to end up providing umbrella support for all types of neuroimaging.

But Im open to other names. Any suggestions?

**Comment by rob-luke** [comment]
I can rename if required. But closing now.

**Comment by Tokazama** [comment]
I've only heard a select group of neurophysiology focused people ever refer to neuroimaging as anything other than MRI. Even in my lab where most people focus on EEG nobody would call it neuroimaging.

**Comment by rob-luke** [comment]
I regularly refer to EEG as a neuroimaging technique. Google scholar reports many papers with the term. By definition EEG, MEG, fNIRS are all methods to image neural activity (and that I plan to add to this package). Hence I am closing this discussion.
