### ISSUE TITLE
Change name to Electrophysiology.jl

### ISSUE THREAD

**Issue by rob-luke** [rob-luke/Neuroimaging.jl#6]
How to change name of a package safely?

**Comment by gear** [comment]
Hi, 
I believe this issue was discussed [here](https://github.com/JuliaStats/Distance.jl/issues/25) before:
Apparently, they created a new repo, migrated the old one to the new one as an old version, and print warning on load and says change to the new one.

**Comment by rob-luke** [comment]
Thanks @gear.
Also see [julia-users](https://groups.google.com/forum/#!topic/julia-users/WYGAG6GhInc)

**Comment by gear** [comment]
Thanks @codles.
By the way, I am using this EEG package for my project. I read on the documentation page that you want to know if someone is using your package. Thank you for your work!

**Comment by rob-luke** [comment]
Thanks for letting me know. I wasn't sure if anyone had seen it :) Do you use EEG? What type of potentials do you look at? Also check out [brainwave.jl](https://github.com/sam81/BrainWave.jl) from @sam81.

Im thinking of making some structural changes eg #5. So if you have any things you like or dislike about the package as is, let me know.

**Comment by gear** [comment]
Thank you very much, @codles, for your suggestion. I am looking at ERP for cognitive and motor events. My main objective is to create a probabilistic generative model for functional brain mapping. Right now I am trying to build a temporal belief network (proposed at NIPS 2015) for Two class motor imagery dataset classification as a baby learning project.

I am a very beginner in this area. If you have time for some advice or guidance, I would be more than grateful to listen. :)

**Comment by rob-luke** [comment]
Jump on gitter sometime and let me know what ERP you are looking at, and we can discuss if we need to modify any of the code to encompass ERP processing.

Also I see you are using Julia v0.5, I haven't tested EEG.jl against the new releases. You may encounter some issues.

**Comment by gear** [comment]
For EEG.jl I am using v0.4.5 now. EEG.jl failed to load with v0.5-beta.

**Comment by rob-luke** [comment]
Created a new repo [here](https://github.com/codles/Electrophysiology.jl).

For now EEG.jl will remain my stable package. And Electrophysiology.jl will be a newer, more Julian implementation.
